In [667]:
import pandas as pd
import requests
import time
import plotly.express as px

In [668]:
cities = {
    "Lahore": {"lat": 31.5204, "lon": 74.3587},
    "Karachi": {"lat": 24.8607, "lon": 67.0011},
    "Islamabad": {"lat": 33.6844, "lon": 73.0479},
    "Rawalpindi": {"lat": 33.5651, "lon": 73.0169},
    "Faisalabad": {"lat": 31.4504, "lon": 73.1350},
    "Multan": {"lat": 30.1575, "lon": 71.5249},
    "Peshawar": {"lat": 34.0151, "lon": 71.5249},
    "Quetta": {"lat": 30.1798, "lon": 66.9750},
    "Rahim Yar Khan": {"lat": 28.4197, "lon": 70.3035},
    "Sialkot": {"lat": 32.4945, "lon": 74.5229}
}

In [669]:
start_date = "2026-03-01"
end_date = "2026-06-26"   # aaj ki date tak; agar tum June 30 tak chaho to "2026-06-30" kar do

all_city_data = []

for city, coord in cities.items():
    print("Downloading data for:", city)

    url = "https://air-quality-api.open-meteo.com/v1/air-quality"

    params = {
        "latitude": coord["lat"],
        "longitude": coord["lon"],
        "hourly": "pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10",
        "start_date": start_date,
        "end_date": end_date,
        "timezone": "Asia/Karachi"
    }

    response = requests.get(url, params=params)

    print(city, "Status:", response.status_code)

    data = response.json()

    if "hourly" in data:
        temp_df = pd.DataFrame(data["hourly"])
        temp_df["city"] = city
        temp_df["latitude"] = coord["lat"]
        temp_df["longitude"] = coord["lon"]
        all_city_data.append(temp_df)
    else:
        print("Problem for", city)
        print(data)

    time.sleep(1)

updated_df = pd.concat(all_city_data, ignore_index=True)

updated_df.head()

Downloading data for: Lahore
Lahore Status: 200
Downloading data for: Karachi
Karachi Status: 200
Downloading data for: Islamabad
Islamabad Status: 200
Downloading data for: Rawalpindi
Rawalpindi Status: 200
Downloading data for: Faisalabad
Faisalabad Status: 200
Downloading data for: Multan
Multan Status: 200
Downloading data for: Peshawar
Peshawar Status: 200
Downloading data for: Quetta
Quetta Status: 200
Downloading data for: Rahim Yar Khan
Rahim Yar Khan Status: 200
Downloading data for: Sialkot
Sialkot Status: 200

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude
0,2026-03-01T00:00,77.1,53.4,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587
1,2026-03-01T01:00,79.4,55.3,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587
2,2026-03-01T02:00,83.8,58.2,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587
3,2026-03-01T03:00,88.7,61.0,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587
4,2026-03-01T04:00,92.4,62.9,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587

In [670]:
updated_df["time"] = pd.to_datetime(updated_df["time"])

updated_df["date"] = updated_df["time"].dt.date
updated_df["hour"] = updated_df["time"].dt.hour
updated_df["month"] = updated_df["time"].dt.strftime("%b %Y")

updated_df.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude,date,hour,month
0,2026-03-01 00:00:00,77.1,53.4,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587,2026-03-01,0,Mar 2026
1,2026-03-01 01:00:00,79.4,55.3,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587,2026-03-01,1,Mar 2026
2,2026-03-01 02:00:00,83.8,58.2,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587,2026-03-01,2,Mar 2026
3,2026-03-01 03:00:00,88.7,61.0,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587,2026-03-01,3,Mar 2026
4,2026-03-01 04:00:00,92.4,62.9,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587,2026-03-01,4,Mar 2026

In [671]:
print("Start Date:", updated_df["time"].min())
print("End Date:", updated_df["time"].max())

updated_df["month"].value_counts().sort_index()

Start Date: 2026-03-01 00:00:00
End Date: 2026-06-26 23:00:00

month
Apr 2026    7200
Jun 2026    6240
Mar 2026    7440
May 2026    7440
Name: count, dtype: int64

In [672]:
df = updated_df.copy()

city_col = "city"
date_col = "time"
pollutant_col = "pm2_5"
aqi_col = "us_aqi"

df.head()

,time,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude,date,hour,month
0,2026-03-01 00:00:00,77.1,53.4,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587,2026-03-01,0,Mar 2026
1,2026-03-01 01:00:00,79.4,55.3,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587,2026-03-01,1,Mar 2026
2,2026-03-01 02:00:00,83.8,58.2,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587,2026-03-01,2,Mar 2026
3,2026-03-01 03:00:00,88.7,61.0,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587,2026-03-01,3,Mar 2026
4,2026-03-01 04:00:00,92.4,62.9,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587,2026-03-01,4,Mar 2026

In [673]:
def classify_aqi(aqi):
    if pd.isna(aqi):
        return "Unknown"
    elif aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Unhealthy for Sensitive Groups"
    elif aqi <= 200:
        return "Unhealthy"
    elif aqi <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df["aqi_category"] = df[aqi_col].apply(classify_aqi)

risk_score_map = {
    "Good": 1,
    "Moderate": 2,
    "Unhealthy for Sensitive Groups": 3,
    "Unhealthy": 4,
    "Very Unhealthy": 5,
    "Hazardous": 6,
    "Unknown": 0
}

df["health_risk_score"] = df["aqi_category"].map(risk_score_map)

df[["city", "time", "pm2_5", "us_aqi", "aqi_category", "health_risk_score"]].head()

,city,time,pm2_5,us_aqi,aqi_category,health_risk_score
0,Lahore,2026-03-01 00:00:00,53.4,152,Unhealthy,4
1,Lahore,2026-03-01 01:00:00,55.3,151,Unhealthy,4
2,Lahore,2026-03-01 02:00:00,58.2,150,Unhealthy for Sensitive Groups,3
3,Lahore,2026-03-01 03:00:00,61.0,149,Unhealthy for Sensitive Groups,3
4,Lahore,2026-03-01 04:00:00,62.9,146,Unhealthy for Sensitive Groups,3

In [674]:
df.to_csv("updated_pakistan_air_quality_mar_jun_2026.csv", index=False)

print("Updated dataset saved successfully!")
print(df.shape)

Updated dataset saved successfully!
(28320, 18)

In [675]:
monthly_trend = df.groupby(["month", "city"], as_index=False)["pm2_5"].mean()

month_order = ["Mar 2026", "Apr 2026", "May 2026", "Jun 2026"]

fig = px.line(
    monthly_trend,
    x="month",
    y="pm2_5",
    color="city",
    title="Updated Monthly PM2.5 Pollution Trend by City: March to June 2026",
    markers=True,
    category_orders={"month": month_order}
)

fig.show()

## Updated Air Quality Data Collection: March to June 2026

In this section, I collected updated air quality data using a public API instead of using only the old Kaggle dataset. This makes the project more current and useful.

In [676]:
import pandas as pd
import requests
import time
import plotly.express as px

In [677]:
cities = {
    "Lahore": {"lat": 31.5204, "lon": 74.3587},
    "Karachi": {"lat": 24.8607, "lon": 67.0011},
    "Islamabad": {"lat": 33.6844, "lon": 73.0479},
    "Rawalpindi": {"lat": 33.5651, "lon": 73.0169},
    "Faisalabad": {"lat": 31.4504, "lon": 73.1350},
    "Multan": {"lat": 30.1575, "lon": 71.5249},
    "Peshawar": {"lat": 34.0151, "lon": 71.5249},
    "Quetta": {"lat": 30.1798, "lon": 66.9750},
    "Rahim Yar Khan": {"lat": 28.4197, "lon": 70.3035},
    "Sialkot": {"lat": 32.4945, "lon": 74.5229}
}

In [678]:
start_date = "2026-03-01"
end_date = "2026-06-26"

all_city_data = []

for city, coord in cities.items():
    print("Downloading:", city)

    url = "https://air-quality-api.open-meteo.com/v1/air-quality"

    params = {
        "latitude": coord["lat"],
        "longitude": coord["lon"],
        "hourly": "pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10",
        "start_date": start_date,
        "end_date": end_date,
        "timezone": "Asia/Karachi"
    }

    response = requests.get(url, params=params)
    print(city, "Status:", response.status_code)

    data = response.json()

    if "hourly" in data:
        temp_df = pd.DataFrame(data["hourly"])
        temp_df["city"] = city
        temp_df["latitude"] = coord["lat"]
        temp_df["longitude"] = coord["lon"]
        all_city_data.append(temp_df)
    else:
        print("Issue for:", city)
        print(data)

    time.sleep(1)

updated_df = pd.concat(all_city_data, ignore_index=True)

display(updated_df.head())
print("Shape:", updated_df.shape)

Downloading: Lahore
Lahore Status: 200
Downloading: Karachi
Karachi Status: 200
Downloading: Islamabad
Islamabad Status: 200
Downloading: Rawalpindi
Rawalpindi Status: 200
Downloading: Faisalabad
Faisalabad Status: 200
Downloading: Multan
Multan Status: 200
Downloading: Peshawar
Peshawar Status: 200
Downloading: Quetta
Quetta Status: 200
Downloading: Rahim Yar Khan
Rahim Yar Khan Status: 200
Downloading: Sialkot
Sialkot Status: 200

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude
0,2026-03-01T00:00,53.4,77.1,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587
1,2026-03-01T01:00,55.3,79.4,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587
2,2026-03-01T02:00,58.2,83.8,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587
3,2026-03-01T03:00,61.0,88.7,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587
4,2026-03-01T04:00,62.9,92.4,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587

Shape: (28320, 13)

In [679]:
updated_df["time"] = pd.to_datetime(updated_df["time"])

updated_df["date"] = updated_df["time"].dt.date
updated_df["hour"] = updated_df["time"].dt.hour
updated_df["month"] = updated_df["time"].dt.strftime("%b %Y")

display(updated_df.head())

print("Start Date:", updated_df["time"].min())
print("End Date:", updated_df["time"].max())
print(updated_df["month"].value_counts().sort_index())

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude,date,hour,month
0,2026-03-01 00:00:00,53.4,77.1,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587,2026-03-01,0,Mar 2026
1,2026-03-01 01:00:00,55.3,79.4,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587,2026-03-01,1,Mar 2026
2,2026-03-01 02:00:00,58.2,83.8,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587,2026-03-01,2,Mar 2026
3,2026-03-01 03:00:00,61.0,88.7,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587,2026-03-01,3,Mar 2026
4,2026-03-01 04:00:00,62.9,92.4,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587,2026-03-01,4,Mar 2026

Start Date: 2026-03-01 00:00:00
End Date: 2026-06-26 23:00:00
month
Apr 2026    7200
Jun 2026    6240
Mar 2026    7440
May 2026    7440
Name: count, dtype: int64

In [680]:
df = updated_df.copy()

city_col = "city"
date_col = "time"
pollutant_col = "pm2_5"
aqi_col = "us_aqi"

display(df.head())
print(df.columns.tolist())

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude,date,hour,month
0,2026-03-01 00:00:00,53.4,77.1,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587,2026-03-01,0,Mar 2026
1,2026-03-01 01:00:00,55.3,79.4,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587,2026-03-01,1,Mar 2026
2,2026-03-01 02:00:00,58.2,83.8,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587,2026-03-01,2,Mar 2026
3,2026-03-01 03:00:00,61.0,88.7,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587,2026-03-01,3,Mar 2026
4,2026-03-01 04:00:00,62.9,92.4,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587,2026-03-01,4,Mar 2026

['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'us_aqi', 'us_aqi_pm2_5', 'us_aqi_pm10', 'city', 'latitude', 'longitude', 'date', 'hour', 'month']

In [681]:
def classify_aqi(aqi):
    if pd.isna(aqi):
        return "Unknown"
    elif aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Unhealthy for Sensitive Groups"
    elif aqi <= 200:
        return "Unhealthy"
    elif aqi <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df["aqi_category"] = df[aqi_col].apply(classify_aqi)

risk_score_map = {
    "Good": 1,
    "Moderate": 2,
    "Unhealthy for Sensitive Groups": 3,
    "Unhealthy": 4,
    "Very Unhealthy": 5,
    "Hazardous": 6,
    "Unknown": 0
}

df["health_risk_score"] = df["aqi_category"].map(risk_score_map)

display(df[["city", "time", "pm2_5", "us_aqi", "aqi_category", "health_risk_score"]].head())

,city,time,pm2_5,us_aqi,aqi_category,health_risk_score
0,Lahore,2026-03-01 00:00:00,53.4,152,Unhealthy,4
1,Lahore,2026-03-01 01:00:00,55.3,151,Unhealthy,4
2,Lahore,2026-03-01 02:00:00,58.2,150,Unhealthy for Sensitive Groups,3
3,Lahore,2026-03-01 03:00:00,61.0,149,Unhealthy for Sensitive Groups,3
4,Lahore,2026-03-01 04:00:00,62.9,146,Unhealthy for Sensitive Groups,3

In [682]:
monthly_trend = df.groupby(["month", "city"], as_index=False)["pm2_5"].mean()

month_order = ["Mar 2026", "Apr 2026", "May 2026", "Jun 2026"]

fig = px.line(
    monthly_trend,
    x="month",
    y="pm2_5",
    color="city",
    title="Updated Monthly PM2.5 Pollution Trend by City: March to June 2026",
    markers=True,
    category_orders={"month": month_order}
)

fig.show()

In [683]:
city_summary = df.groupby("city").agg(
    average_pm25=("pm2_5", "mean"),
    average_aqi=("us_aqi", "mean"),
    max_aqi=("us_aqi", "max"),
    average_health_risk=("health_risk_score", "mean"),
    total_records=("us_aqi", "count")
).reset_index()

city_summary = city_summary.sort_values("average_aqi", ascending=False)

display(city_summary)

fig = px.bar(
    city_summary,
    x="city",
    y="average_aqi",
    title="Updated Average AQI by Pakistani City",
    text=city_summary["average_aqi"].round(2)
)

fig.show()

,city,average_pm25,average_aqi,max_aqi,average_health_risk,total_records
0,Faisalabad,54.027048,137.181144,268,3.306850,2832
4,Multan,50.267832,129.360523,226,3.132768,2832
3,Lahore,42.651554,122.320268,306,2.954096,2832
9,Sialkot,39.951412,113.990819,188,2.770127,2832
7,Rahim Yar Khan,34.480473,100.454802,169,2.462571,2832
6,Quetta,26.270516,99.843927,332,2.526836,2832
5,Peshawar,30.319103,95.490466,208,2.381356,2832
1,Islamabad,27.665148,93.386299,204,2.367585,2832
8,Rawalpindi,27.665148,93.386299,204,2.367585,2832
2,Karachi,24.603743,78.575918,161,2.098164,2832

In [684]:
df = updated_df.copy()

city_col = "city"
date_col = "time"
pollutant_col = "pm2_5"
aqi_col = "us_aqi"

display(df.head())
print("Rows and Columns:", df.shape)
print("Columns:", df.columns.tolist())

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude,date,hour,month
0,2026-03-01 00:00:00,53.4,77.1,993.0,28.4,12.0,66.0,152,152,63,Lahore,31.5204,74.3587,2026-03-01,0,Mar 2026
1,2026-03-01 01:00:00,55.3,79.4,862.0,25.0,11.4,65.0,151,151,62,Lahore,31.5204,74.3587,2026-03-01,1,Mar 2026
2,2026-03-01 02:00:00,58.2,83.8,767.0,22.3,11.0,64.0,150,150,62,Lahore,31.5204,74.3587,2026-03-01,2,Mar 2026
3,2026-03-01 03:00:00,61.0,88.7,699.0,19.8,10.8,62.0,149,149,62,Lahore,31.5204,74.3587,2026-03-01,3,Mar 2026
4,2026-03-01 04:00:00,62.9,92.4,665.0,18.1,10.7,60.0,146,146,61,Lahore,31.5204,74.3587,2026-03-01,4,Mar 2026

Rows and Columns: (28320, 16)
Columns: ['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'us_aqi', 'us_aqi_pm2_5', 'us_aqi_pm10', 'city', 'latitude', 'longitude', 'date', 'hour', 'month']

In [685]:
print("Missing values:")
df.isnull().sum()

Missing values:

time                0
pm2_5               0
pm10                0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
us_aqi              0
us_aqi_pm2_5        0
us_aqi_pm10         0
city                0
latitude            0
longitude           0
date                0
hour                0
month               0
dtype: int64

In [686]:
def classify_aqi(aqi):
    if pd.isna(aqi):
        return "Unknown"
    elif aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Unhealthy for Sensitive Groups"
    elif aqi <= 200:
        return "Unhealthy"
    elif aqi <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df["aqi_category"] = df[aqi_col].apply(classify_aqi)

risk_score_map = {
    "Good": 1,
    "Moderate": 2,
    "Unhealthy for Sensitive Groups": 3,
    "Unhealthy": 4,
    "Very Unhealthy": 5,
    "Hazardous": 6,
    "Unknown": 0
}

df["health_risk_score"] = df["aqi_category"].map(risk_score_map)

display(df[["city", "time", "pm2_5", "us_aqi", "aqi_category", "health_risk_score"]].head())

,city,time,pm2_5,us_aqi,aqi_category,health_risk_score
0,Lahore,2026-03-01 00:00:00,53.4,152,Unhealthy,4
1,Lahore,2026-03-01 01:00:00,55.3,151,Unhealthy,4
2,Lahore,2026-03-01 02:00:00,58.2,150,Unhealthy for Sensitive Groups,3
3,Lahore,2026-03-01 03:00:00,61.0,149,Unhealthy for Sensitive Groups,3
4,Lahore,2026-03-01 04:00:00,62.9,146,Unhealthy for Sensitive Groups,3

In [687]:
city_summary = df.groupby("city").agg(
    average_pm25=("pm2_5", "mean"),
    average_aqi=("us_aqi", "mean"),
    max_aqi=("us_aqi", "max"),
    min_aqi=("us_aqi", "min"),
    average_health_risk=("health_risk_score", "mean"),
    total_records=("us_aqi", "count")
).reset_index()

city_summary = city_summary.sort_values("average_aqi", ascending=False)

display(city_summary)

,city,average_pm25,average_aqi,max_aqi,min_aqi,average_health_risk,total_records
0,Faisalabad,54.027048,137.181144,268,65,3.306850,2832
4,Multan,50.267832,129.360523,226,67,3.132768,2832
3,Lahore,42.651554,122.320268,306,59,2.954096,2832
9,Sialkot,39.951412,113.990819,188,58,2.770127,2832
7,Rahim Yar Khan,34.480473,100.454802,169,60,2.462571,2832
6,Quetta,26.270516,99.843927,332,33,2.526836,2832
5,Peshawar,30.319103,95.490466,208,42,2.381356,2832
1,Islamabad,27.665148,93.386299,204,53,2.367585,2832
8,Rawalpindi,27.665148,93.386299,204,53,2.367585,2832
2,Karachi,24.603743,78.575918,161,32,2.098164,2832

In [688]:
fig = px.bar(
    city_summary,
    x="city",
    y="average_aqi",
    title="Updated Average AQI by Pakistani City: March to June 2026",
    text=city_summary["average_aqi"].round(2)
)

fig.show()

In [689]:
monthly_trend = df.groupby(["month", "city"], as_index=False)["pm2_5"].mean()

month_order = ["Mar 2026", "Apr 2026", "May 2026", "Jun 2026"]

fig = px.line(
    monthly_trend,
    x="month",
    y="pm2_5",
    color="city",
    title="Updated Monthly PM2.5 Pollution Trend by City: March to June 2026",
    markers=True,
    category_orders={"month": month_order}
)

fig.show()

In [690]:
risk_counts = df["aqi_category"].value_counts().reset_index()
risk_counts.columns = ["aqi_category", "count"]

display(risk_counts)

fig = px.pie(
    risk_counts,
    names="aqi_category",
    values="count",
    title="AQI Health Risk Category Distribution: March to June 2026"
)

fig.show()

                     aqi_category  count
0                        Moderate  14563
1  Unhealthy for Sensitive Groups   9185
2                       Unhealthy   4258
3                            Good    154
4                  Very Unhealthy    153
5                       Hazardous      7

In [691]:
hourly_pattern = df.groupby(["hour", "city"], as_index=False)["pm2_5"].mean()

fig = px.line(
    hourly_pattern,
    x="hour",
    y="pm2_5",
    color="city",
    title="Hourly PM2.5 Pollution Pattern by City",
    markers=True
)

fig.show()

In [692]:
multan_df = df[df["city"].str.lower() == "multan"]

print("Multan Records:", multan_df.shape)
display(multan_df.head())

multan_summary = multan_df.groupby("hour", as_index=False)["pm2_5"].mean()

fig = px.line(
    multan_summary,
    x="hour",
    y="pm2_5",
    title="Multan Hourly PM2.5 Pollution Pattern",
    markers=True
)

fig.show()

Multan Records: (2832, 18)

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,us_aqi,us_aqi_pm2_5,us_aqi_pm10,city,latitude,longitude,date,hour,month,aqi_category,health_risk_score
14160,2026-03-01 00:00:00,78.9,92.0,1310.0,19.1,12.0,70.0,164,164,73,Multan,30.1575,71.5249,2026-03-01,0,Mar 2026,Unhealthy,4
14161,2026-03-01 01:00:00,82.7,97.3,1359.0,21.7,11.7,62.0,163,163,72,Multan,30.1575,71.5249,2026-03-01,1,Mar 2026,Unhealthy,4
14162,2026-03-01 02:00:00,88.0,103.6,1404.0,25.0,11.6,55.0,162,162,71,Multan,30.1575,71.5249,2026-03-01,2,Mar 2026,Unhealthy,4
14163,2026-03-01 03:00:00,94.1,111.1,1431.0,29.9,12.1,48.0,161,161,70,Multan,30.1575,71.5249,2026-03-01,3,Mar 2026,Unhealthy,4
14164,2026-03-01 04:00:00,100.6,117.8,1455.0,35.5,12.8,41.0,161,161,69,Multan,30.1575,71.5249,2026-03-01,4,Mar 2026,Unhealthy,4

In [693]:
df.to_csv("updated_pakistan_air_quality_mar_jun_2026.csv", index=False)
city_summary.to_csv("updated_city_aqi_summary_mar_jun_2026.csv", index=False)

print("Files saved successfully!")
print("Main file: updated_pakistan_air_quality_mar_jun_2026.csv")
print("Summary file: updated_city_aqi_summary_mar_jun_2026.csv")

Files saved successfully!
Main file: updated_pakistan_air_quality_mar_jun_2026.csv
Summary file: updated_city_aqi_summary_mar_jun_2026.csv

## Task 1: Web Scraping

In this section, I scraped air pollution and smog-related news headlines for Pakistan. The purpose is to understand how air pollution is being discussed in public/news sources.

In [694]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

query = "Pakistan air pollution smog"
url = "https://news.google.com/rss/search?q=" + query.replace(" ", "+") + "&hl=en-PK&gl=PK&ceid=PK:en"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

soup = BeautifulSoup(response.content, "xml")

items = soup.find_all("item")

news_data = []

for item in items[:50]:
    title = item.title.text if item.title else None
    link = item.link.text if item.link else None
    pub_date = item.pubDate.text if item.pubDate else None
    source = item.source.text if item.source else None

    news_data.append({
        "title": title,
        "source": source,
        "published_date": pub_date,
        "link": link
    })

news_df = pd.DataFrame(news_data)

display(news_df.head())
print("Total headlines scraped:", news_df.shape[0])

Status Code: 200

,title,source,published_date,link
0,Lahore Air Quality Index (AQI) and Pakistan Ai...,IQAir,"Mon, 22 Jun 2026 20:56:38 GMT",https://news.google.com/rss/articles/CBMiZ0FVX...
1,Pakistan Air Quality Index (AQI) and Air Pollu...,IQAir,"Mon, 22 Jun 2026 20:51:02 GMT",https://news.google.com/rss/articles/CBMiVEFVX...
2,Pakistan world’s most polluted country in 2025...,Al Jazeera,"Tue, 24 Mar 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMimAFBV...
3,"Pakistan ranked most polluted country in 2025,...",Dawn,"Tue, 24 Mar 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiSEFVX...
4,Karachi Air Quality Index (AQI) and Pakistan A...,IQAir,"Mon, 22 Jun 2026 20:54:04 GMT",https://news.google.com/rss/articles/CBMiZ0FVX...

Total headlines scraped: 50

## Task 4: Sentiment Analysis

In this section, I applied sentiment analysis on the scraped news headlines. Each headline is classified as Positive, Neutral, or Negative.

In [695]:
import nltk

nltk.download("vader_lexicon")

from nltk.sentiment.vader import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [696]:
def get_sentiment(text):
    score = sia.polarity_scores(str(text))["compound"]

    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

news_df["sentiment"] = news_df["title"].apply(get_sentiment)

display(news_df.head(10))

,title,source,published_date,link,sentiment
0,Lahore Air Quality Index (AQI) and Pakistan Ai...,IQAir,"Mon, 22 Jun 2026 20:56:38 GMT",https://news.google.com/rss/articles/CBMiZ0FVX...,Neutral
1,Pakistan Air Quality Index (AQI) and Air Pollu...,IQAir,"Mon, 22 Jun 2026 20:51:02 GMT",https://news.google.com/rss/articles/CBMiVEFVX...,Neutral
2,Pakistan world’s most polluted country in 2025...,Al Jazeera,"Tue, 24 Mar 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMimAFBV...,Negative
3,"Pakistan ranked most polluted country in 2025,...",Dawn,"Tue, 24 Mar 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMiSEFVX...,Negative
4,Karachi Air Quality Index (AQI) and Pakistan A...,IQAir,"Mon, 22 Jun 2026 20:54:04 GMT",https://news.google.com/rss/articles/CBMiZ0FVX...,Neutral
5,Worsening Smog In Pakistan Demands Sustainable...,The Friday Times,"Mon, 23 Feb 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMivwFBV...,Negative
6,Pakistan tops global pollution rankings in 202...,Firstpost,"Tue, 24 Mar 2026 07:00:00 GMT",https://news.google.com/rss/articles/CBMixAFBV...,Positive
7,Smog season never ends: Pakistan’s DIY clean-a...,Malay Mail,"Thu, 22 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMivAFBV...,Negative
8,Smog chokes Pakistan's Punjab as air quality s...,ANI News,"Sun, 18 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMiwwFBV...,Negative
9,Smog tightens grip on Punjab; Lahore’s Air Qua...,The Express Tribune,"Sat, 17 Jan 2026 08:00:00 GMT",https://news.google.com/rss/articles/CBMivwFBV...,Negative

In [697]:
sentiment_counts = news_df["sentiment"].value_counts().reset_index()
sentiment_counts.columns = ["sentiment", "count"]

display(sentiment_counts)

  sentiment  count
0  Negative     35
1   Neutral      9
2  Positive      6

In [698]:
fig = px.bar(
    sentiment_counts,
    x="sentiment",
    y="count",
    title="Sentiment Analysis of Pakistan Air Pollution News Headlines",
    text="count"
)

fig.show()

In [699]:
news_df.to_csv("scraped_air_pollution_news_sentiment.csv", index=False)

print("Scraped news sentiment file saved successfully!")

Scraped news sentiment file saved successfully!

## Final Conclusion

This project analyzed updated air quality data for Pakistani cities from March to June 2026. The analysis compared city-level AQI, PM2.5 trends, hourly pollution patterns, and health risk categories.

The project also included web scraping of Pakistan air pollution and smog-related news headlines. Sentiment analysis was applied to classify the headlines as Positive, Neutral, or Negative.

Overall, this project covers all four CodeAlpha Data Analytics tasks:
- Web Scraping
- Exploratory Data Analysis
- Data Visualization
- Sentiment Analysis

The results can help understand pollution patterns, identify high-risk cities, and observe how air pollution is discussed in news sources.

In [700]:
df.to_csv("updated_pakistan_air_quality_mar_jun_2026.csv", index=False)
city_summary.to_csv("updated_city_aqi_summary_mar_jun_2026.csv", index=False)
news_df.to_csv("scraped_air_pollution_news_sentiment.csv", index=False)

print("All files saved successfully!")

All files saved successfully!

In [701]:
from google.colab import files

files.download("updated_pakistan_air_quality_mar_jun_2026.csv")
files.download("updated_city_aqi_summary_mar_jun_2026.csv")
files.download("scraped_air_pollution_news_sentiment.csv")

In [702]:
df.to_csv("updated_pakistan_air_quality_mar_jun_2026.csv", index=False)
city_summary.to_csv("updated_city_aqi_summary_mar_jun_2026.csv", index=False)
news_df.to_csv("scraped_air_pollution_news_sentiment.csv", index=False)

print("All files saved successfully!")

All files saved successfully!

In [703]:
from google.colab import files

files.download("updated_pakistan_air_quality_mar_jun_2026.csv")